# Generated by Django 6.0.5 on 2026-05-14 02:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('camera_source', models.CharField(max_length=255)),
                ('threshold', models.FloatField(default=0.6)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Persistent ID encoded in the student's QR code", unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('student_class', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, default='', max_length=150)),
                ('area', models.CharField(blank=True, default='', max_length=150)),
                ('work_schedule', models.CharField(blank=True, default='', max_length=100)),
                ('dni', models.CharField(blank=True, default='', help_text='DNI / national ID number printed on the fotocheck', max_length=20)),
                ('image', models.ImageField(upload_to='students/')),
                ('authorized', models.BooleanField(default=False)),
                ('qr_code', models.ImageField(blank=True, help_text='Auto-generated QR image (UUID encoded) with institutional logo', null=True, upload_to='qrcodes/')),
                ('qr_active', models.BooleanField(default=True, help_text="Disable to block this student's QR from marking attendance")),
                ('face_crop', models.ImageField(blank=True, help_text='Circular face crop (auto-generated from photo)', null=True, upload_to='faces/')),
                ('fotocheck_png', models.ImageField(blank=True, help_text='Institutional ID card — 86×54 mm @ 300 DPI PNG', null=True, upload_to='fotochecks/')),
                ('fotocheck_pdf', models.FileField(blank=True, help_text='Institutional ID card — print-ready PDF 86×54 mm', null=True, upload_to='fotochecks/')),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_recognition_enabled', models.BooleanField(default=True)),
                ('qr_enabled', models.BooleanField(default=True)),
                ('checkout_delay_minutes', models.PositiveIntegerField(default=10)),
                ('display_throttle_seconds', models.PositiveIntegerField(default=5)),
                ('recognition_threshold', models.FloatField(default=0.6)),
            ],
            options={
                'verbose_name': 'System Configuration',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.student')),
            ],
        ),
    ]
